kind: pipeline
type: kubernetes
name: docker-images

steps:
- name: microservice-base
  image: plugins/docker
  settings:
    repo: jevon82/microservice-base
    context: microservice-base
    dockerfile: microservice-base/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password