kind: pipeline
type: kubernetes
name: docker-images

steps:
- name: microservice-base
  image: plugins/docker
  settings:
    repo: jevon82/microservice-base
    context: microservice-base
    dockerfile: microservice-base/Dockerfile
    cache_from: "jevon82/microservice-base:latest"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: golang-builder-alpine
  image: plugins/docker
  settings:
    repo: jevon82/golang-builder-alpine
    context: golang-builder-alpine
    dockerfile: golang-builder-alpine/Dockerfile
    cache_from: "jevon82/golang-builder-alpine:latest"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password      